# Generated by Django 4.1.3 on 2022-11-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_verification',
            new_name='is_verified',
        ),
    ]
